ALTER TABLE "admins" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "campaigns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competencies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "respondents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competency_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "analysis_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "telegram_update_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competency_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "campaign_role_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competency_ratings" ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" FROM "anon", "authenticated";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" FROM "anon", "authenticated";

ALTER DEFAULT PRIVILEGES IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon", "authenticated";
ALTER DEFAULT PRIVILEGES IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon", "authenticated";
